### ISSUE TITLE
[BUG] configs are broken

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#309] opened 2024-05-22 00:47 UTC
Configs in [mov-cli.scrapers] don't work anymore

If I have a namespace like
```
[Mov-cli.scrapers]
vid1 = "films.vadapav"
```
The `` mov-cli -s vid1`` option does not work anymore

And so it is for everything else... including yt costom namspase with pre defined config for no audio

Eg: `` yt-a = {namespace = "yout1.default", options.audio = true, options.shorts = false } ``

What's the most frustrating is, downgrading to the previus version dosent do anything to bring back the config functionality... can u also explain why after updating, when downgrading is like nothing changes or that the old features in previus versions are like scalpeld away???

**Comment by ananasmoe** [comment] 2024-05-22 04:22
> Configs in [mov-cli.scrapers] don't work anymore

I can't reproduce this issue.

> What's the most frustrating is, downgrading to the previus version dosent do anything to bring back the config functionality... can u also explain why after updating, when downgrading is like nothing changes or that the old features in previus versions are like scalpeld away???

It's currently only supported on mov-cli v4.4.

Which can be installed with:
```
pip install mov-cli==4.4a3 -U
```

**Comment by EbanNox** [comment] 2024-05-22 06:37
> > Configs in [mov-cli.scrapers] don't work anymore
> 
> I can't reproduce this issue.
> 
> > What's the most frustrating is, downgrading to the previus version dosent do anything to bring back the config functionality... can u also explain why after updating, when downgrading is like nothing changes or that the old features in previus versions are like scalpeld away???
> 
> It's currently only supported on mov-cli v4.4.
> 
> Which can be installed with:
> ```
> pip install mov-cli==4.4a3 -U
> ```

What r u talking about.... this features where implemented eather sins or or before 4.3.13

And this is the feature I am referring to just to make shure we are on the same page:
https://github.com/mov-cli/mov-cli/issues/291#issuecomment-2077605906

And don't say no, becose I had it and I even tested it several times... it worked... and even updated when 4.3.14 came out and it still worked... now on the latest it vanished...

But if I am going craizy, is there a way to check on termux or with python in termux a version history , eg: when whas witch version downloaded and installed and when, if so, how?

**Comment by ananasmoe** [comment] 2024-05-22 08:40
![image](https://github.com/mov-cli/mov-cli/assets/132799819/d53e519d-69ba-4f46-9180-3ea3ab3d55e0)

**Comment by THEGOLDENPRO** [comment] 2024-05-22 13:05
yeah Ananas is right, this is a v4.4 feature and v4.4 still hasn't been merged into the stable branch (v4) hence it's instead an [alpha release](https://pypi.org/project/mov-cli/4.4a3/) on pypi.

**Comment by THEGOLDENPRO** [comment] 2024-05-22 13:09
I know it's a bit confusing, sorry for that but essentially v4.3 is currently in what we call a "feature freeze", meaning features will not be added to it until v4.4. The only updates allowed on v4.3 are major or specific bug fixes, hence why you see releases still being made.

**Closed as completed** 2024-05-24 11:13 UTC
Labels: bug
