### ISSUE TITLE
[BUG]AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by stargaz21** [mov-cli/mov-cli#327] opened 2024-06-15 15:33 UTC
**Describe the bug:**
When I use the -d command and use the Films plugin to get the file, pick what scraper i want to use

**Expected behavior:**
When I use the command mov-cli -d followed by the movie name it will give me a option to select what scraper I want to use and the it will download the movie.

**Steps to reproduce:**

1. mov-cli -d "name of movie"

**Screenshots:**

**Logs:**

```python
{terminal output}
```

**Platform:**

 - OS: 
 - Version: 

**Additional context / possible cause or solution:**

**Version**

**Comment by ananasmoe** [comment] 2024-06-15 15:34
Send a full log please.

**Comment by THEGOLDENPRO** [comment] 2024-06-15 16:26
Potentially a duplicate of #325 but please send your terminal output here for us to confirm.

**Closed as completed** 2024-06-18 14:36 UTC
Labels: bug
