### ISSUE TITLE
[BUG] release mov-cli empty after self build

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#150] opened 2023-06-14 11:43 UTC
**Describe the bug**
I'm trying to package them for the mpr, it's like AUR but for debs. Under Debian 12, by copying from the AUR PKGBUID, they both turn out to be empty (only the egg folder).

**Error**
No errors.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Version: latest stable and latest git.

**Additional context**

It seams to work in Arch.

**Possible cause**
* There's a bug in Debian 12, it just got released.
* The toml file has an error.

**Comment by ghost** [comment] 2023-06-15 21:50
a ok, the git version builds correctly

**Comment by ghost** [comment] 2023-06-15 21:53
yea, just make sure that the release is buildable

**Comment by Poseidon444** [comment] 2023-06-26 14:32
i'll look into it

**Comment by ghost** [comment] 2023-07-05 11:00
Ignore the crash i reported earlier.

**Comment by ghost** [comment] 2023-07-06 20:17
i try `python3 -m build --no-isolation --wheel` inside the release folder, the wheel is 16K. I do the same in the git repo, it's 63K.

I copy `.git` in the release folder, build, and now the wheel is 63K.

**Comment by 4cecoder** [comment] 2024-02-10 18:02
Please include the general links for Debian's package manager process and repository info

I'll have a look at the toml stuff too
@pirate486743186 @Poseidon444

**Comment by THEGOLDENPRO** [comment] 2024-03-14 12:29
V3 has been deprecated. V4 can be installed on Linux with make using:
```sh
make install
```
Or without make like:
```sh
pip install . -U
```

It can be built into tar and wheel files with:
```sh
make
```
Or:
```sh
python -m build
```

**Comment by ghost** [comment] 2024-03-22 17:58
@THEGOLDENPRO 
It's still present in v4 (wheel empty after build on debian)
python-inquirer has the same problem. https://github.com/magmax/python-inquirer/issues/544

**Comment by THEGOLDENPRO** [comment] 2024-03-22 20:53
> @THEGOLDENPRO It's still present in v4 (wheel empty after build on debian) python-inquirer has the same problem. [magmax/python-inquirer#544](https://github.com/magmax/python-inquirer/issues/544)

I don't remember having difficulty building python-inquirer (probably is fine on arch) but I was having this same problem with mov-cli when I was working on an arch package for it. (https://github.com/THEGOLDENPRO/arch-mov-cli)

I know why it's happening with mov-cli, it's an issue I've encountered for a whole year with python's build tools. I actually fixed it in this commit but it ended up breaking other stuff so it had to be reverted: https://github.com/mov-cli/mov-cli/commit/434c03c6b862ce4f7425ecb55dca19a8ea8dc95e

I'm going to try to fix this once again, I think I just missed some important config lines that time.

**Comment by THEGOLDENPRO** [comment] 2024-03-22 21:40
Could you try mov-cli from the [empty-wheel](https://github.com/mov-cli/mov-cli/tree/fix/empty-wheel) branch, I think the problem is fixed there.

**Comment by THEGOLDENPRO** [comment] 2024-03-22 21:48
Also I'm starting to realise packaging mov-cli is going to be pain at the moment as individual plugins will also have to be packaged individually (at least that's how I want to package it; feel free to package it however, it'll be marked as third party anyways) as the plugins have to be in the same environment for mov-cli to find them. In our case it has to be installed with the same python installation.

**Comment by ghost** [comment] 2024-03-23 00:26
it seams to work.

**Comment by EbanNox** [comment] 2024-03-23 06:11
> Also I'm starting to realise packaging mov-cli is going to be pain at the moment as individual plugins will also have to be packaged individually (at least that's how I want to package it; feel free to package it however, it'll be marked as third party anyways) as the plugins have to be in the same environment for mov-cli to find them. In our case it has to be installed with the same python installation.

We could make an automated pipeline that does this for us. Making diferent packaging for both mov-cli and the plugins (that we make) and have them all automatically packaged and meybe even auto uploaded , all this via a single build script

**Comment by THEGOLDENPRO** [comment] 2024-03-23 12:35
> > Also I'm starting to realise packaging mov-cli is going to be pain at the moment as individual plugins will also have to be packaged individually (at least that's how I want to package it; feel free to package it however, it'll be marked as third party anyways) as the plugins have to be in the same environment for mov-cli to find them. In our case it has to be installed with the same python installation.
> 
> We could make an automated pipeline that does this for us. Making diferent packaging for both mov-cli and the plugins (that we make) and have them all automatically packaged and meybe even auto uploaded , all this via a single build script

Yeah that's how it would normally be done but the issue is more of one needs to be created for every plugin and every popular distribution and not every plugin is made by us so you'll have plugins that don't have distribution packages at all making the distro package of mov-cli quite useless as it can't include them.

I'm trying to find out if there's somehow a way to have mov-cli import modules (plugins in our case) from other python installations. Or perhaps even inject with pipx.

**Closed as completed** 2024-03-23 14:56 UTC
Labels: bug, v3
