### ISSUE TITLE
[BUG] mov-cli 1.4.7 windows & android unrunnable

### ISSUE THREAD

**Issue by EbanNox** [mov-cli/mov-cli#167] opened 2023-07-25 21:12 UTC
The latest version of miv-cli is unrunnable. Every time I try to run it it throws me back a error stating that some files are missing

**Comment by EbanNox** [comment] 2023-07-25 23:15
Mey it be that there is nothing wrong with the build it self, but only something wrong in the pip repository? Meybe the package was incorrecty built in repository?

**Comment by Cosmicom16** [comment] 2023-07-26 01:20
On Android, a `/home/[user]` directory is called instead of something like `/data/data/com.Termux/files/home/`, which may not work with Termux, but you can manually edit it in `props.py` under the `utils` directory in the installation in `site-packages`. I also noticed that `provider.mov-cli` was moved from `~` to `~/.config/mov-cli` between 1.4.6 and 1.4.7, so you may need to make the appropriate directories or again just edit `props.py`.

**Comment by ghost** [comment] 2023-07-26 11:36
`~/.config/mov-cli` is meant for linux, not android.

**Comment by Cosmicom16** [comment] 2023-07-26 12:47
Yes, but `platform.system()` returns `linux` for Android and no check is made in the `home()` function to remedy that. However there is a check in `utils/player.py` under the `os` property that could be reused.

**Comment by EbanNox** [comment] 2023-07-26 20:55
Well, the install went well today , , yesterday I re did the instal many times and it did not work, but today it did, but it still don't work , now it launches and I can select providers etc, but after selecting a episode or movie , I keep getting either a token error or a base64 error. I am ok my phone curently  but tomorrow I'll screenshot the error on windows that I keep getting

**Comment by MrLDasVino** [comment] 2023-07-26 22:59
> Well, the install went well today , , yesterday I re did the instal many times and it did not work, but today it did, but it still don't work , now it launches and I can select providers etc, but after selecting a episode or movie , I keep getting either a token error or a base64 error. I am ok my phone curently but tomorrow I'll screenshot the error on windows that I keep getting

Its being worked on, there is no point in trying till the issues are resolved in the next update as mentioned here #158 
since any videos that use dokicloud as the host wont work at the moment which is basically all of mov-cli

**Comment by EbanNox** [comment] 2023-07-28 18:29
> > Well, the install went well today , , yesterday I re did the instal many times and it did not work, but today it did, but it still don't work , now it launches and I can select providers etc, but after selecting a episode or movie , I keep getting either a token error or a base64 error. I am ok my phone curently but tomorrow I'll screenshot the error on windows that I keep getting
> 
> Its being worked on, there is no point in trying till the issues are resolved in the next update as mentioned here #158 since any videos that use dokicloud as the host wont work at the moment which is basically all of mov-cli

anything new?

**Comment by MrLDasVino** [comment] 2023-07-28 19:34
> > > Well, the install went well today , , yesterday I re did the instal many times and it did not work, but today it did, but it still don't work , now it launches and I can select providers etc, but after selecting a episode or movie , I keep getting either a token error or a base64 error. I am ok my phone curently but tomorrow I'll screenshot the error on windows that I keep getting
> > 
> > 
> > Its being worked on, there is no point in trying till the issues are resolved in the next update as mentioned here #158 since any videos that use dokicloud as the host wont work at the moment which is basically all of mov-cli
> 
> anything new?

Not yet, usually you can see it on the main page of the project, the last updates were a few days ago

**Comment by ananasmoe** [comment] 2023-07-29 02:42
So Android needs to be checked again, as it was changed.

**Comment by THEGOLDENPRO** [comment] 2023-07-29 12:58
yep, I can confirm too that the last update broke Android as from what I can tell we switched back to using files again. I fixed this the last time we introduced these files over -> [**here**](https://github.com/mov-cli/mov-cli/pull/77/commits/a7f0dbffb1d699f7e64255ae61dc1bbf0f9e477e#diff-eda2dce693068f67b7e392129ba9bc11a83bf7995f626463d07ab986534ee398R17)

It should be a pretty easy fix. When I have the time later, I'll work on this issue.

**Comment by THEGOLDENPRO** [comment] 2023-07-29 13:07
also whenever you guys decide to release a new mov-cli version feel free to mention me on GitHub or Discord, I can test and make sure everything is functioning correctly on Android Termux before an actual release. My tag is `g0ldy_`, I'm in the ani-cli discord.

**Comment by EbanNox** [comment] 2023-07-30 16:04
> So Android needs to be checked again, as it was changed.

I will do this later today and send in anything if I get any

**Comment by ghost** [comment] 2023-08-18 20:31
This is still not solved? I'm proposing the use of this library
https://github.com/platformdirs/platformdirs

**Comment by ananasmoe** [comment] 2023-08-28 20:29
Should be fixed, if not open a new issue.

**Closed as completed by ananasmoe** 2023-08-28 20:29 UTC
Labels: bug

**Comment by THEGOLDENPRO** [comment] 2023-09-04 18:15
> This is still not solved? I'm proposing the use of this library https://github.com/platformdirs/platformdirs

👍 I'll take advantage of this library in the v4 rewrite. Thanks
