### ISSUE TITLE
Please make it support subtitles [FEATURE]

### ISSUE THREAD

**Issue by Agatha66** [mov-cli/mov-cli#202] opened 2023-11-13 18:00 UTC
i really love it if it can supports subtitles with different kind of languages

**Comment by ananasmoe** [comment] 2023-11-25 21:14
Will be added with v4.

**Comment by THEGOLDENPRO** [comment] 2024-03-14 12:21
Also this should be the issue to track -> #79

**Comment by THEGOLDENPRO** [comment] 2024-03-17 02:18
Closing this as it's a duplicate of #79

**Closed as completed** 2024-03-17 02:18 UTC
Labels: enhancement, v3
